export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  publishedDate: string; // ISO
  readTime: string;
  category: string;
  relatedService?: string; // service slug
  content: string[]; // paragraphs; strings starting with "## " render as subheadings, "- " as list items
};

export const blogPosts: BlogPost[] = [
  {
    slug: "signs-you-need-a-new-roof",
    title: "7 Signs You Need a New Roof (Not Just a Repair)",
    excerpt:
      "Not sure if that leak is a quick fix or a sign of bigger problems? Here's how to tell the difference between a roof repair and a full replacement.",
    publishedDate: "2026-06-02",
    readTime: "5 min read",
    category: "Roofing",
    relatedService: "roofing",
    content: [
      "Every roof eventually reaches a point where patching the next leak stops making financial sense. The tricky part is knowing when you've crossed that line. Here are the signs worth paying attention to.",
      "## 1. Your roof is nearing or past its expected lifespan",
      "Most asphalt shingle roofs in Ontario are rated for 20-25 years, though harsh winters, ice damming, and wind exposure can shorten that. If you don't know how old your roof is, checking your home's inspection report or asking your realtor from when you purchased is a good starting point.",
      "## 2. Shingles are curling, cracking, or missing granules",
      "Curling or clawing shingles mean the material is losing flexibility and its ability to shed water. If you find granules collecting in your gutters or at the base of downspouts, the protective coating is wearing away faster than it should.",
      "## 3. You're seeing daylight in the attic",
      "Head up to the attic on a sunny day with the lights off. Any pinpricks of light coming through the roof deck mean water can get through too, even if you haven't noticed a leak yet.",
      "## 4. Repeated leaks in different spots",
      "One leak is a repair. Leaks that keep showing up in new locations after each storm usually mean the underlying roofing system, not just a single shingle or flashing point, has failed.",
      "## 5. Sagging rooflines",
      "A roof deck that visibly sags between rafters is a structural concern, not a cosmetic one, and should be assessed promptly.",
      "## 6. Moss, algae, or dark streaking across large areas",
      "Some staining is cosmetic, but widespread moss growth can trap moisture against the shingles and accelerate deterioration underneath.",
      "## 7. Your energy bills have crept up",
      "Aging roofing and ventilation systems lose their ability to regulate attic temperature, which can show up as higher heating and cooling costs.",
      "## When in doubt, get a professional opinion",
      "A quick inspection can usually tell you whether you're looking at a targeted repair or a full replacement, and catching it early is almost always cheaper than waiting for a leak to cause interior damage.",
      "Ironmark Exteriors offers free roof inspections and estimates for homeowners across Hamilton, Stoney Creek, Burlington, Ancaster, and Dundas. If any of the signs above sound familiar, reach out and we'll take a look.",
    ],
  },
  {
    slug: "vinyl-vs-fiber-cement-siding",
    title: "Vinyl vs. Fiber Cement Siding: Which Is Right for Your Home?",
    excerpt:
      "Both are popular siding choices for Ontario homes, but they differ in cost, durability, maintenance, and style. Here's how to decide.",
    publishedDate: "2026-06-16",
    readTime: "6 min read",
    category: "Siding",
    relatedService: "siding",
    content: [
      "Siding is one of the biggest visual and functional upgrades you can make to a home's exterior, and vinyl and fiber cement are the two most common options homeowners in our area choose between. Neither is universally better, the right pick depends on your priorities.",
      "## Vinyl siding",
      "Vinyl is the most widely installed siding material in North America for good reason: it's affordable, low-maintenance, and comes in a wide range of colors and profiles.",
      "- Lower upfront cost than fiber cement",
      "- Never needs painting, color is baked into the material",
      "- Resistant to rot and insect damage",
      "- Lighter weight, generally faster to install",
      "- Can fade over time with prolonged sun exposure",
      "- Less impact-resistant than fiber cement in extreme weather",
      "## Fiber cement siding",
      "Fiber cement (like James Hardie board) is a composite of cement, sand, and cellulose fibers, engineered to mimic the look of wood without the maintenance burden.",
      "- Higher upfront cost, but often adds more resale value",
      "- Extremely durable, resists fire, impact, and pests",
      "- Holds paint well and can be refreshed with a new color down the road",
      "- Heavier material, typically requires more labor to install",
      "- Needs occasional repainting or resealing over its lifespan",
      "## Our take",
      "If you want the lowest-maintenance option and are working with a tighter budget, vinyl is a proven, reliable choice. If you're prioritizing long-term durability, a more premium look, or planning to stay in the home for decades, fiber cement is worth the investment.",
      "We install and repair both vinyl and fiber cement siding for homes throughout Hamilton and the surrounding areas. If you're not sure which fits your home and budget, we're happy to walk through the options during a free estimate.",
    ],
  },
  {
    slug: "how-often-clean-gutters",
    title: "How Often Should You Clean Your Gutters in Ontario?",
    excerpt:
      "Clogged gutters cause more home damage than most homeowners realize. Here's a practical cleaning schedule for Ontario's climate.",
    publishedDate: "2026-06-30",
    readTime: "4 min read",
    category: "Gutters",
    relatedService: "gutters",
    content: [
      "Gutters have one job: move water away from your roof, siding, and foundation. When they're clogged, that water backs up and ends up exactly where you don't want it, behind fascia boards, into your basement, or pooling around your foundation.",
      "## A general cleaning schedule",
      "- Late spring: after trees have finished flowering and shedding seed pods",
      "- Late fall: after most leaves have dropped, before winter freeze",
      "- After major storms: high winds can knock debris into gutters even outside the usual seasons",
      "Homes surrounded by mature trees may need an additional mid-summer check, while homes with few nearby trees can often get away with the two seasonal cleanings alone.",
      "## Signs your gutters need attention now",
      "- Water spilling over the sides during rain instead of flowing through downspouts",
      "- Sagging or pulling-away gutter sections",
      "- Plant growth visible in the gutter itself",
      "- Water stains or streaking on the siding beneath the gutter line",
      "## Gutter guards can reduce (not eliminate) the work",
      "Gutter guards cut down significantly on debris buildup, especially on homes with heavy tree cover, but they don't remove the need for occasional maintenance entirely, fine debris and granules can still accumulate over time.",
      "## Why this matters more than it seems",
      "Overflowing gutters are one of the most common and most preventable causes of fascia rot, basement leaks, and foundation issues we see on service calls. A cleaning that takes an hour or two twice a year is far cheaper than the repairs that follow years of neglect.",
      "Ironmark Exteriors offers gutter cleaning, repair, and gutter guard installation for homeowners across Hamilton, Stoney Creek, Burlington, Ancaster, and Dundas.",
    ],
  },
  {
    slug: "best-time-to-paint-house-exterior",
    title: "When Is the Best Time to Paint Your House Exterior in Ontario?",
    excerpt:
      "Timing your exterior paint job around Ontario's weather makes a real difference in how long the finish lasts. Here's what to consider.",
    publishedDate: "2026-07-07",
    readTime: "4 min read",
    category: "Painting",
    relatedService: "painting",
    content: [
      "Exterior paint doesn't just need dry weather to go on, it needs the right temperature and humidity range to cure properly. Get the timing wrong and even a good paint job can fail early through peeling, blistering, or poor adhesion.",
      "## The ideal window",
      "Late spring through early fall is generally the most reliable stretch in our climate, once overnight temperatures are consistently staying above the range most exterior paints require to cure, and before the first fall frost.",
      "## Why temperature swings matter",
      "Paint applied when it's too cold won't cure properly and can crack prematurely. Paint applied in direct, intense midday heat can dry too fast on the surface before it's bonded properly underneath, leading to poor adhesion.",
      "## Humidity and rain matter too",
      "Freshly applied paint needs dry time before rain hits it, most products need several hours of dry weather minimum, and high humidity slows curing even without rain. A trustworthy painting crew will track the forecast closely rather than just checking for clear skies on the day of.",
      "## Don't ignore surface prep",
      "Regardless of timing, the paint job is only as good as the prep work underneath, scraping loose paint, sanding rough spots, and priming bare wood or repaired areas. Rushed prep is the most common reason a paint job fails early, more often than timing issues.",
      "## Planning ahead helps",
      "Because the good-weather window is limited, painting contractors in our area tend to book up through the summer months. If you're planning an exterior paint job, reaching out in early spring gives you the best shot at your preferred timing.",
      "Ironmark Exteriors provides exterior painting for homes throughout Hamilton and surrounding areas, including full house painting, trim and soffit work, and deck staining.",
    ],
  },
  {
    slug: "prepare-home-exterior-for-winter",
    title: "How to Prepare Your Home's Exterior for an Ontario Winter",
    excerpt:
      "A little prep in the fall can prevent a lot of expensive damage once the snow and ice arrive. Here's a practical exterior winterizing checklist.",
    publishedDate: "2026-07-21",
    readTime: "5 min read",
    category: "Maintenance",
    content: [
      "Ontario winters are hard on a home's exterior, freeze-thaw cycles, ice damming, and heavy snow loads all put stress on roofing, siding, and gutters. A fall walkthrough can catch small issues before they become winter emergencies.",
      "## 1. Clear and inspect the gutters",
      "Clogged gutters are one of the leading causes of ice dams, where melting snow refreezes at the roof edge and forces water back under the shingles. Clean gutters drain properly and reduce that risk significantly.",
      "## 2. Check the roof for loose or damaged shingles",
      "Any shingle that's loose, cracked, or missing before winter is an entry point for water once snow starts melting and refreezing on the roof. This is the easiest time of year to catch and fix it.",
      "## 3. Inspect flashing around chimneys, vents, and skylights",
      "These transition points are common leak sources. A quick visual check, or a professional inspection, can catch gaps before they let water in during a thaw.",
      "## 4. Look at siding for gaps or damage",
      "Cracked or loose siding panels let moisture behind the wall assembly, where it can freeze and cause more damage than the original crack. Small repairs now are far cheaper than what follows a winter of freeze-thaw cycles.",
      "## 5. Trim back tree branches near the roofline",
      "Heavy snow and ice can snap overhanging branches, and a falling limb can do serious damage to shingles or gutters.",
      "## 6. Make sure downspouts direct water away from the foundation",
      "Water that pools near the foundation and then freezes can contribute to cracking over time. Downspout extensions are a simple, inexpensive fix.",
      "## When to call a professional",
      "If you're not comfortable getting on a ladder, or you notice anything that looks like more than routine wear, a professional inspection before winter is worth the peace of mind, it's far easier to fix a problem in October than in the middle of a January thaw.",
      "Ironmark Exteriors offers free exterior inspections for homeowners in Hamilton, Stoney Creek, Burlington, Ancaster, and Dundas heading into the winter season.",
    ],
  },
  {
    slug: "benefits-of-pressure-washing-before-selling",
    title: "Why Pressure Washing Is One of the Best ROI Home Improvements Before Selling",
    excerpt:
      "Curb appeal sells houses. Here's why a professional pressure wash is one of the cheapest, fastest ways to improve first impressions.",
    publishedDate: "2026-07-28",
    readTime: "4 min read",
    category: "Pressure Washing",
    relatedService: "pressure-washing",
    content: [
      "When homeowners think about improving curb appeal before listing, they often jump straight to landscaping or a fresh coat of paint. Pressure washing is cheaper, faster, and often makes a bigger visual difference than either.",
      "## First impressions happen in seconds",
      "Buyers form an opinion about a home before they even walk through the front door. Dirt, algae staining, and grime buildup on siding, walkways, and driveways read as neglect, even if the home is well maintained inside.",
      "## What pressure washing actually removes",
      "- Algae and mold streaking on siding, especially on north-facing walls",
      "- Dirt and grime buildup on driveways and walkways",
      "- Pollen and organic staining on decks and fences",
      "- Grime accumulated in gutter exteriors and soffits",
      "## It's also good prep work",
      "If you're planning to paint before selling, pressure washing is a necessary first step, paint doesn't adhere well over dirt and mildew, so this isn't just cosmetic, it protects the investment in a fresh paint job too.",
      "## A same-day improvement",
      "Unlike landscaping or renovations that take weeks, a professional pressure wash is typically a same-day service with an immediate, visible result, which makes it one of the best value-for-time improvements before putting a home on the market.",
      "Ironmark Exteriors provides pressure washing for siding, driveways, walkways, decks, and fences across Hamilton, Stoney Creek, Burlington, Ancaster, and Dundas.",
    ],
  },
  {
    slug: "roof-repair-cost-hamilton",
    title: "What Affects Roof Repair Cost in Hamilton, ON",
    excerpt:
      "Roof repair pricing varies a lot depending on the type and size of the damage. Here's what actually drives the cost, and how to get an accurate quote.",
    publishedDate: "2026-09-15",
    readTime: "5 min read",
    category: "Roofing",
    relatedService: "roofing",
    content: [
      "\"How much does roof repair cost?\" is one of the most common questions we get from homeowners in Hamilton, and it's a hard one to answer with a single number, because the price depends heavily on what's actually wrong. Here's a breakdown of the factors that drive cost up or down.",
      "## Size and location of the damage",
      "A small area of missing or damaged shingles near the ridge is a very different job than a leak that's spread across a valley or around a chimney. Repairs in hard-to-reach spots, like steep pitches or areas requiring extra scaffolding, also cost more due to the added labour and safety setup.",
      "## What's actually damaged",
      "Not all roof problems are the same. A few missing shingles is a straightforward fix. Damaged flashing around a chimney, vent, or skylight involves more careful work to reseal properly. If water has gotten into the roof deck itself, the repair may involve replacing sections of wood underneath the shingles, which adds materials and labour.",
      "## Age and condition of the surrounding roof",
      "If the roof around the damaged area is old and brittle, matching shingles safely without cracking more of them takes more time and care than working on a newer roof. In some cases, a roof that's near the end of its life makes more financial sense to replace than to keep patching, our inspection will tell you honestly which situation you're in.",
      "## Access and safety requirements",
      "Steep roofs, high roofs, and homes with limited ladder access all add time and equipment needs to a job, which affects the final price.",
      "## Why a phone estimate rarely works",
      "Because so much depends on what the damage actually looks like up close, we don't quote roof repairs over the phone. A short in-person inspection lets us give you an accurate, itemized quote instead of a rough guess that could be off in either direction.",
      "## Getting an accurate quote",
      "The best way to know your actual roof repair cost in Hamilton is a free inspection. We'll look at the damage, explain what's causing it, and give you a clear price before any work starts, no surprise charges once the crew is on the roof.",
      "Ironmark Exteriors offers free roof inspections and repair estimates for homeowners across Hamilton, Stoney Creek, Burlington, and the surrounding areas.",
    ],
  },
  {
    slug: "repair-or-replace-siding",
    title: "Can You Repair Siding Instead of Replacing It? A Homeowner's Guide",
    excerpt:
      "A cracked or loose panel doesn't always mean a full re-side. Here's how to tell when a siding repair makes sense and when it doesn't.",
    publishedDate: "2026-09-22",
    readTime: "5 min read",
    category: "Siding",
    relatedService: "siding",
    content: [
      "One of the most common questions we get on a siding call is whether the damage can just be repaired, or whether it's going to turn into a full re-side. The honest answer is: it depends on how much damage there is and how old the rest of the siding is, not on which option costs more for us to do.",
      "## When repair usually makes sense",
      "- The damage is limited to one panel or a small, contained section",
      "- The rest of the siding is still structurally sound",
      "- A reasonably close colour and profile match is available",
      "- There's no sign of moisture damage behind the panel",
      "If your siding checks those boxes, a repair is almost always the more practical choice, there's no reason to replace a whole wall of siding that's otherwise performing fine because of one cracked panel.",
      "## When replacement starts to make more sense",
      "- Damage is spread across multiple panels or multiple walls",
      "- The siding is old enough that matching material isn't available",
      "- Moisture has already reached the sheathing or framing underneath",
      "- You're already planning an upgrade for appearance or insulation",
      "In these cases, chasing individual repairs often ends up costing more over time than addressing the wall properly once.",
      "## Why matching matters more than people expect",
      "Vinyl siding fades with sun exposure, which means a brand-new panel next to 10-year-old siding can be a noticeable colour mismatch even when the profile is identical. We'll always tell you upfront how close a match is realistic before starting any repair work, rather than surprising you after the fact.",
      "## What causes most of the siding damage we see",
      "Cold-weather brittleness is the biggest one, vinyl cracks much more easily below freezing than it does in summer, so an impact that wouldn't leave a mark in July can crack a panel in January. Wind-loosened panels and separated seams are the next most common, especially on homes with more direct wind exposure.",
      "## Getting an accurate answer for your home",
      "A phone estimate for siding repair is really just a guess, the only way to know whether you're looking at a repair or a full re-side is to actually see the damage. Photos are often enough to get a realistic starting range before booking an in-person look.",
      "Ironmark Exteriors repairs and replaces siding for homeowners across Hamilton, Stoney Creek, Burlington, Ancaster, and Dundas. Send us photos of the damage and we'll give you an honest read on repair versus replacement.",
    ],
  },
  {
    slug: "are-gutter-guards-worth-it",
    title: "Are Gutter Guards Worth It in Ontario? What They Actually Prevent",
    excerpt:
      "Gutter guards aren't a magic fix, but they do cut down on maintenance significantly for the right homes. Here's what they prevent and what they don't.",
    publishedDate: "2026-09-29",
    readTime: "4 min read",
    category: "Gutters",
    relatedService: "gutter-guards",
    content: [
      "Gutter guards come up in almost every conversation about reducing how often gutters need cleaning, and for good reason, they genuinely cut down on debris buildup. But they're often sold as a complete fix when the reality is more nuanced.",
      "## What gutter guards actually prevent",
      "- Leaves and larger debris from collecting in the gutter channel",
      "- Nesting materials from birds and small animals",
      "- Clogged downspouts from larger debris working its way down",
      "- The need for frequent seasonal cleanings on heavily treed properties",
      "## What they don't prevent",
      "Fine debris like pine needles, shingle grit, and seed pods can still find their way past most guard systems over time. Guards also don't eliminate the need for any maintenance, an occasional check, especially after a big storm, is still worth doing.",
      "## Who benefits the most",
      "Homes with heavy tree cover see the biggest difference, properties that were needing two or three cleanings a year often drop to one, or an occasional check instead of a full cleaning. Homes with little nearby tree cover see a smaller practical benefit, since there's less debris to block in the first place.",
      "## Ice dam considerations",
      "Gutter guards can also help reduce ice dam risk indirectly, by keeping gutters clearer heading into winter, there's less standing water to freeze and expand against the roofline in the first place.",
      "## Are they worth the upfront cost?",
      "For homes with significant tree cover, yes, the reduction in cleaning frequency usually pays for the guards within a few years. For homes with minimal trees nearby, the math is less clear-cut, and a twice-yearly cleaning schedule might be the more cost-effective choice.",
      "Ironmark Exteriors supplies and installs gutter guards for homeowners across Hamilton, Stoney Creek, Burlington, Ancaster, and Dundas, fitted to new or existing gutter systems.",
    ],
  },
  {
    slug: "soffit-fascia-damage-signs-causes",
    title: "Soffit and Fascia Damage: Signs, Causes, and Why It Matters",
    excerpt:
      "Soffit and fascia don't get much attention until something's visibly wrong, by then pests or water may already be in. Here's what to watch for.",
    publishedDate: "2026-10-01",
    readTime: "5 min read",
    category: "Exterior Maintenance",
    relatedService: "soffit-fascia-repair",
    content: [
      "Soffit and fascia are easy to overlook, they're not something most homeowners think about until there's a visible problem. But they do real work: fascia supports your gutters and closes off the edge of the roof deck, while soffit ventilates the attic and keeps pests out of the eaves.",
      "## Common signs of damage",
      "- Soft or spongy spots when you press on the fascia board",
      "- Visible gaps or missing sections along the soffit",
      "- Peeling paint or dark staining on the fascia",
      "- Birds, wasps, or squirrels getting into the attic or eaves",
      "- Gutters sagging or pulling away from the roofline",
      "- A musty smell or visible moisture in the attic near the eaves",
      "## What usually causes it",
      "A gutter leak sitting against the fascia board is one of the most common causes we see, water that would otherwise drain away instead sits against the wood, and over a season or two that's enough to start rot. Blocked gutters that overflow directly onto the fascia cause the same problem faster. Simple age and paint wear on original wood trim is the other major factor, especially on older homes.",
      "## Why it's worth addressing early",
      "Once fascia board rots, it stops supporting the gutter properly, which can let the gutter sag or pull away entirely. The gap that creates gives water and pests a direct path into the roof structure, turning what would have been a small trim repair into something that touches the roof deck. Catching it early is almost always a smaller, cheaper job.",
      "## The pest connection",
      "Gaps in damaged soffit are one of the most common ways squirrels, birds, and wasps get into an attic. If you're hearing noises in the attic or finding insect activity near the eaves, it's worth checking the soffit before assuming it's a pest-control-only problem, sealing the entry point is usually part of the actual fix.",
      "## When a repair is enough",
      "Most soffit and fascia issues are contained to one section, a board rotted near a downspout, a panel pulled loose by wind, and can be repaired without touching the whole eave. We only recommend a full run replacement when the damage is already widespread.",
      "Ironmark Exteriors repairs and replaces soffit and fascia for homeowners across Hamilton, Stoney Creek, Burlington, Ancaster, and Dundas, including the ventilation and pest-entry issues that often come with it.",
    ],
  },
  {
    slug: "why-downspouts-matter",
    title: "Why Your Downspouts Matter More Than You Think",
    excerpt:
      "Downspouts are the most overlooked part of a gutter system, and one of the most common causes of foundation and basement issues when they fail.",
    publishedDate: "2026-10-07",
    readTime: "4 min read",
    category: "Gutters",
    relatedService: "downspout-repair",
    content: [
      "Gutters get most of the attention, but downspouts are doing the more important job: actually carrying water away from your foundation instead of just catching it off the roof. A gutter system with a blocked, disconnected, or undersized downspout isn't really protecting your home, it's just relocating the problem to ground level.",
      "## Signs your downspouts need attention",
      "- Water pooling near the foundation after rain",
      "- A downspout that's visibly disconnected from the gutter above",
      "- Water spilling out partway down instead of reaching the bottom",
      "- Erosion or staining on the ground directly below a downspout",
      "- A basement that gets damp after heavy rain",
      "## Why disconnected downspouts are a bigger deal than they look",
      "A downspout that's come loose from the gutter, often from ice, a ladder, or just age, dumps water right against the foundation instead of carrying it several feet away. Over repeated rain events, that's enough to contribute to basement dampness or, in worse cases, foundation cracking.",
      "## Undersized downspouts are a common, less obvious problem",
      "Some homes, especially older ones, have downspouts that were never sized for the volume of water a modern roof area sheds during a heavy storm. The gutter itself can be in good condition and still overflow if the downspout can't keep up, which is sometimes mistaken for a gutter problem when it's really a downspout sizing issue.",
      "## Extensions matter more than homeowners expect",
      "Even a properly connected downspout isn't doing its full job if it dumps water two feet from the foundation instead of six or eight. Downspout extensions are one of the cheapest, simplest fixes available, and often the single best thing you can do to reduce water pooling near your foundation.",
      "## A quick way to check your own home",
      "During the next heavy rain, take a look at where each downspout is actually sending water. If you see pooling, erosion, or water running back toward the house instead of away from it, that's worth a repair call before it becomes a bigger issue.",
      "Ironmark Exteriors repairs, reattaches, extends, and installs downspouts for homeowners across Hamilton, Stoney Creek, Burlington, Ancaster, and Dundas.",
    ],
  },
];

export function getBlogPost(slug: string) {
  return blogPosts.find((p) => p.slug === slug);
}
