/**
 * City-specific process intro and seasonal-care content for the gutter
 * cleaning city pages that share the [area] template (Hamilton and Stoney
 * Creek have their own bespoke pages with their own hand-written content).
 * Keyed by city slug rather than rotated by index, since this content
 * references real local geography and should stay tied to the correct
 * city rather than being interchangeable.
 */
export type GutterCleaningCityContent = {
  processIntro: string;
  seasonal: string[];
};

export const gutterCleaningCityContent: Record<string, GutterCleaningCityContent> = {
  burlington: {
    processIntro:
      "Burlington homes near the Lake Ontario shoreline deal with more wind-blown debris and humidity than inland areas, so we follow the same six steps on every job to make sure nothing gets missed.",
    seasonal: [
      "Being close to Lake Ontario means Burlington homes, especially around Aldershot and the escarpment-facing streets, catch more wind-driven leaves and organic debris than homes further inland. That buildup traps moisture against the fascia longer than dry debris would.",
      "Fall cleanup after leaf drop is the busiest season locally, but a spring visit matters just as much here. Lake-effect weather through the winter brings freeze-thaw swings that can loosen brackets or crack sealant on a gutter that went into winter already clogged.",
      "Homes in older Burlington neighbourhoods with mature tree canopy, like parts of Roseland and Millcroft, tend to need a mid-season check between the two seasonal cleanings, particularly after a windy stretch off the lake.",
    ],
  },
  brantford: {
    processIntro:
      "Many homes we service near the Grand River in Brantford are older builds with narrower or original eavestrough, so our crews pay close attention to condition, not just debris, at every step.",
    seasonal: [
      "Brantford's older housing stock, common in areas like Eagle Place and Holmedale, often has gutters that have been repainted or patched over the years. Debris buildup on an aging system causes problems faster than it would on newer eavestrough.",
      "Fall is the peak season for cleaning once trees along residential streets and near the Grand River have dropped their leaves, and a spring cleaning clears out whatever built up over winter.",
      "Ontario's freeze-thaw cycle affects Brantford the same way it does the rest of the region: water trapped in a clogged gutter over winter can freeze, expand, and stress old seams or fasteners that newer systems would handle without issue.",
    ],
  },
  grimsby: {
    processIntro:
      "Grimsby sits along the Niagara Escarpment and the lake, and homes here often deal with heavier tree cover than newer subdivisions, so we check every section carefully, not just the obvious spots.",
    seasonal: [
      "The escarpment and lakeside setting around Grimsby on the Lake and the older parts of downtown Grimsby mean a lot of mature trees close to homes, which means more leaves and organic debris finding their way into gutters through the fall.",
      "Because the area sees a mix of lake-effect weather and escarpment winds, gutters here can fill up faster after a single storm than homes further from the water. A fall cleaning after leaf drop and a spring check after winter cover the two periods that matter most.",
      "Freeze-thaw cycles are common through the winter months, and a gutter that's already clogged going into a cold snap is far more likely to develop cracked seams or loosened brackets by spring.",
    ],
  },
  "st-catharines": {
    processIntro:
      "St. Catharines homes near the Welland Canal and older neighbourhoods like Port Dalhousie often have mature trees and older gutter systems, so we inspect condition as closely as we clean debris.",
    seasonal: [
      "Older, established streets around Port Dalhousie and Western Hill tend to have larger, mature trees than newer developments, which means more consistent leaf and seed buildup through spring and fall.",
      "The Niagara region's humidity, combined with proximity to the canal and Lake Ontario, means debris in a clogged gutter can hold moisture longer, adding weight and accelerating wear on fasteners and seams.",
      "A fall cleaning after leaves have dropped and a spring cleaning after winter cover most homes, but properties with heavy tree cover in older parts of the city often benefit from a mid-season check as well.",
    ],
  },
  "niagara-falls": {
    processIntro:
      "Niagara Falls properties, from residential streets in Chippawa to homes near the tourist corridor, see a mix of tree debris and the extra humidity the falls area is known for, so we test drainage carefully on every job.",
    seasonal: [
      "The mist and humidity generated by the falls settle over a wider area than most visitors realize, and that extra moisture means debris sitting in a gutter tends to stay damp longer than it would in a drier inland location.",
      "Residential areas like Chippawa and Stamford have plenty of mature trees, so leaf and seed buildup through spring and fall is common, while properties nearer the tourist corridor deal more with general airborne debris.",
      "Winters bring the same freeze-thaw risk as the rest of the region: standing water in a blocked gutter can freeze and expand, loosening brackets or cracking seams before the spring thaw.",
    ],
  },
};
